//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pulse.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pulse.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autumn.
        /// </summary>
        public static string Autumn {
            get {
                return ResourceManager.GetString("Autumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban Image.
        /// </summary>
        public static string BanImage {
            get {
                return ResourceManager.GetString("BanImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next picture.
        /// </summary>
        public static string NextPicture {
            get {
                return ResourceManager.GetString("NextPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Pulse.
        /// </summary>
        public static string OptionsAbout {
            get {
                return ResourceManager.GetString("OptionsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string OptionsAboutTabHeader {
            get {
                return ResourceManager.GetString("OptionsAboutTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string OptionsApplyButton {
            get {
                return ResourceManager.GetString("OptionsApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviour.
        /// </summary>
        public static string OptionsBehaviour {
            get {
                return ResourceManager.GetString("OptionsBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary files.
        /// </summary>
        public static string OptionsCache {
            get {
                return ResourceManager.GetString("OptionsCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string OptionsCancelButton {
            get {
                return ResourceManager.GetString("OptionsCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set wallpaper as logon background.
        /// </summary>
        public static string OptionsChangeLogonBg {
            get {
                return ResourceManager.GetString("OptionsChangeLogonBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete old pictures.
        /// </summary>
        public static string OptionsClearCache {
            get {
                return ResourceManager.GetString("OptionsClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete pictures downloaded more than {0} ago.
        /// </summary>
        public static string OptionsClearInterval {
            get {
                return ResourceManager.GetString("OptionsClearInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear now.
        /// </summary>
        public static string OptionsClearNow {
            get {
                return ResourceManager.GetString("OptionsClearNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is protected by copyright law and distributed under Microsoft Public License..
        /// </summary>
        public static string OptionsCopyright {
            get {
                return ResourceManager.GetString("OptionsCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string OptionsDay {
            get {
                return ResourceManager.GetString("OptionsDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string OptionsDays {
            get {
                return ResourceManager.GetString("OptionsDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download pictures automatically.
        /// </summary>
        public static string OptionsDownloadAutomatically {
            get {
                return ResourceManager.GetString("OptionsDownloadAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change picture on startup.
        /// </summary>
        public static string OptionsDownloadOnStart {
            get {
                return ResourceManager.GetString("OptionsDownloadOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string OptionsFilter {
            get {
                return ResourceManager.GetString("OptionsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To skip pictures with some content which you don&apos;t want to see, type one or more keywords here. Split words with comma..
        /// </summary>
        public static string OptionsFilterInfo {
            get {
                return ResourceManager.GetString("OptionsFilterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can skip images with unwanted content. Type one or more keywords separated with commas (e.g. &quot;rain, man, animals&quot;)..
        /// </summary>
        public static string OptionsFilterText {
            get {
                return ResourceManager.GetString("OptionsFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string OptionsGeneralTabHeader {
            get {
                return ResourceManager.GetString("OptionsGeneralTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get pictures with max available resolution.
        /// </summary>
        public static string OptionsGetMaxRes {
            get {
                return ResourceManager.GetString("OptionsGetMaxRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h..
        /// </summary>
        public static string OptionsIntervalHours {
            get {
                return ResourceManager.GetString("OptionsIntervalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min..
        /// </summary>
        public static string OptionsIntervalMinutes {
            get {
                return ResourceManager.GetString("OptionsIntervalMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string OptionsLanguage {
            get {
                return ResourceManager.GetString("OptionsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less updates.
        /// </summary>
        public static string OptionsLessUpdates {
            get {
                return ResourceManager.GetString("OptionsLessUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More updates.
        /// </summary>
        public static string OptionsMoreUpdates {
            get {
                return ResourceManager.GetString("OptionsMoreUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newer.
        /// </summary>
        public static string OptionsNewer {
            get {
                return ResourceManager.GetString("OptionsNewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OptionsOkButton {
            get {
                return ResourceManager.GetString("OptionsOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older.
        /// </summary>
        public static string OptionsOlder {
            get {
                return ResourceManager.GetString("OptionsOlder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs.
        /// </summary>
        public static string OptionsOutputs {
            get {
                return ResourceManager.GetString("OptionsOutputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre Fetch.
        /// </summary>
        public static string OptionsPreFetch {
            get {
                return ResourceManager.GetString("OptionsPreFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change picture every:.
        /// </summary>
        public static string OptionsRefreshInterval {
            get {
                return ResourceManager.GetString("OptionsRefreshInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will be applied after restarting the program.
        /// </summary>
        public static string OptionsRestart {
            get {
                return ResourceManager.GetString("OptionsRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string OptionsSearch {
            get {
                return ResourceManager.GetString("OptionsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keyword(s).
        /// </summary>
        public static string OptionsSearchBox {
            get {
                return ResourceManager.GetString("OptionsSearchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures found:.
        /// </summary>
        public static string OptionsSearchResults {
            get {
                return ResourceManager.GetString("OptionsSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select wallpapers source:.
        /// </summary>
        public static string OptionsSelectProvider {
            get {
                return ResourceManager.GetString("OptionsSelectProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip pictures with lower resolution.
        /// </summary>
        public static string OptionsSkipLowRes {
            get {
                return ResourceManager.GetString("OptionsSkipLowRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string OptionsVersion {
            get {
                return ResourceManager.GetString("OptionsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse options.
        /// </summary>
        public static string OptionsWindowTitle {
            get {
                return ResourceManager.GetString("OptionsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ProviderSettings {
            get {
                return ResourceManager.GetString("ProviderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Settings for .
        /// </summary>
        public static string ProviderSettingsTitle {
            get {
                return ResourceManager.GetString("ProviderSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring.
        /// </summary>
        public static string Spring {
            get {
                return ResourceManager.GetString("Spring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer.
        /// </summary>
        public static string Summer {
            get {
                return ResourceManager.GetString("Summer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Cache Folder.
        /// </summary>
        public static string ViewCacheFolder {
            get {
                return ResourceManager.GetString("ViewCacheFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter.
        /// </summary>
        public static string Winter {
            get {
                return ResourceManager.GetString("Winter", resourceCulture);
            }
        }
    }
}
